version: '3'
services:
  elasticsearch:
    build:
      context: ./Elasticsearch
      dockerfile: dockerfile
    container_name: elasticsearch 
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    tty: true

  ubuntu18.04:
    build:
      context: ./Ubuntu18.04
      dockerfile: dockerfile
    container_name: ubuntu18.04
    volumes:
      - ./tokyo2020+1:/home/amano/tokyo2020+1
    ports:
      - 88:8888
    tty: true


