# 仮想化するベースOS
FROM ubuntu:18.04
# 誰が作ったかは入れておきましょう
LABEL maintainer="amano123"

# 各環境変数を設定
ENV USER "amano"
ENV HOME /home/${USER}
ENV DEBCONF_NOWARNINGS yes
ENV SHELL /usr/bin/zsh
ENV UBUNTU_CONTAINER_NAME ubuntu18.04

# 一般ユーザーアカウントを追加
RUN useradd -m ${USER} \
# 一般ユーザーにsudo権限を付与
&&  gpasswd -a ${USER} sudo \
# 一般ユーザーのパスワード設定
&&  echo "${USER}:amano" | chpasswd

# 設定ファイルをコピー
## zsh
COPY .zshrc ${HOME}
## python
COPY ./python3/library/library.txt ${HOME}/library.txt

RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list

RUN set -x \
&&  apt-get update \
&&  apt-get install -y --no-install-recommends \
                sudo \
                zsh \
                vim \
                git \
                ## python3 
                python3 \
                python3-pip \
                iputils-ping \
                ## network
                net-tools \
                ## japanese
                language-pack-ja-base \
                language-pack-ja \
&&  ln -s /usr/bin/python3 /usr/bin/python \
&&  ln -s /usr/bin/pip3 /usr/bin/pip \
&&  apt-get -y clean \
&&  rm -rf /var/lib/apt/lists/* \
&&  locale-gen ja_JP.UTF-8 \
&&  pip3 --no-cache-dir install -I setuptools \
&&  pip3 --no-cache-dir install -Ir \
                ${HOME}/library.txt \
&&  rm -rf ${HOME}/library.txt

RUN jupyter notebook --generate-config \
&&  sed -i -e "s/#c.NotebookApp.pylab = 'disabled'/ \
		          c.NotebookApp.pylab = 'disabled'/" \
		  /home/${USER}/.jupyter/jupyter_notebook_config.py \
&&  sed -i -e "s/#c.NotebookApp.ip = 'localhost'/ \
		          c.NotebookApp.ip = '${UBUNTU_CONTAINER_NAME}'/" \
		  /home/${USER}/.jupyter/jupyter_notebook_config.py \
&&  sed -i -e "s/#c.NotebookApp.token = '<generated>'/ \
		          c.NotebookApp.token = ''/" \
		  /home/${USER}/.jupyter/jupyter_notebook_config.py

# 以降のRUN/CMDを実行するユーザー
USER ${USER}

# 以降の作業ディレクトリを指定
WORKDIR ${HOME}

CMD ["/bin/zsh"]

