# 仮想化するベースOS
FROM ubuntu:18.04
# 誰が作ったかは入れておきましょう
LABEL maintainer="ynkmr"

# 各環境変数を設定
ENV USER "ynkmr"
ENV HOME /home/${USER}
ENV DEBCONF_NOWARNINGS yes
ENV SHELL /usr/bin/bash
ENV UBUNTU_CONTAINER_NAME ubuntu

# 一般ユーザーアカウントを追加
RUN useradd -m ${USER} \
# 一般ユーザーにsudo権限を付与
&&  gpasswd -a ${USER} sudo \
# 一般ユーザーのパスワード設定
&&  echo "${USER}:ynkmr" | chpasswd

# 設定ファイルをコピー
## python
COPY ./python3/library/library.txt ${HOME}/library.txt

RUN sed -i 's@archive.ubuntu.com@ftp.jaist.ac.jp/pub/Linux@g' /etc/apt/sources.list \
&&  set -x \
&&  apt-get update \
&&  apt-get install -y --no-install-recommends \
                sudo \
                vim \
                git \
                ## python3 
                python3 \
                python3-pip \
                iputils-ping \
                ## network
                net-tools \
                ## japanese
                language-pack-ja-base \
                language-pack-ja \
&&  ln -s /usr/bin/python3 /usr/bin/python \
&&  ln -s /usr/bin/pip3 /usr/bin/pip \
&&  apt-get -y clean \
&&  rm -rf /var/lib/apt/lists/* \
&&  locale-gen ja_JP.UTF-8 \
&&  pip3 --no-cache-dir install -I setuptools \
&&  pip3 --no-cache-dir install -Ir \
                ${HOME}/library.txt \
&&  rm -rf ${HOME}/library.txt \
&&  pip install elasticsearch 

# 以降のRUN/CMDを実行するユーザー
USER ${USER}

# 以降の作業ディレクトリを指定
WORKDIR ${HOME}

CMD ["/bin/bash"]