FROM docker.elastic.co/elasticsearch/elasticsearch:7.3.2

# 日本語全文検索pulgin
RUN elasticsearch-plugin install analysis-kuromoji \
&&  elasticsearch-plugin install analysis-icu

RUN touch /usr/share/elasticsearch/config/my_jisho.dic
